In [12]:
import pandas as pd
import statistics
import numpy as np

# Declaration
data = pd.read_csv("Sleep_health_and_lifestyle_dataset.csv")

target_col = ['Age','Sleep Duration','Quality of Sleep','Physical Activity Level','Stress Level','Heart Rate','Daily Steps']

for dt in target_col:
    # Convert to int
    data[dt] = pd.to_numeric(data[dt], errors='coerce')
    
    # Remove NaN
    data = data.dropna(subset=[dt])

    max_val = data[dt].max()
    min_val = data[dt].min()
    range_val = max_val - min_val
    mean = round(data[dt].mean(),2)
    mode = round(statistics.mode(data[dt]),2)
    var = round(np.nanvar(data[dt],ddof=1),2)
    std = round(var ** 0.5,2)

    print(f"Max of {dt.title()} : {max_val}")
    print(f"Min of {dt.title()} : {min_val}")
    print(f"Range of {dt.title()} : {range_val}")
    print(f"Mean of {dt.title()} : {mean}")
    print(f"Mode of {dt.title()} : {mode}")
    print(f"Variance of {dt.title()} : {var}")
    print(f"Standard Deviance of {dt.title()} : {std}\n")

Max of Age : 59
Min of Age : 27
Range of Age : 32
Mean of Age : 42.18
Mode of Age : 43
Variance of Age : 75.22
Standard Deviance of Age : 8.67

Max of Sleep Duration : 8.5
Min of Sleep Duration : 5.8
Range of Sleep Duration : 2.7
Mean of Sleep Duration : 7.13
Mode of Sleep Duration : 7.2
Variance of Sleep Duration : 0.63
Standard Deviance of Sleep Duration : 0.79

Max of Quality Of Sleep : 9
Min of Quality Of Sleep : 4
Range of Quality Of Sleep : 5
Mean of Quality Of Sleep : 7.31
Mode of Quality Of Sleep : 8
Variance of Quality Of Sleep : 1.43
Standard Deviance of Quality Of Sleep : 1.2

Max of Physical Activity Level : 90
Min of Physical Activity Level : 30
Range of Physical Activity Level : 60
Mean of Physical Activity Level : 59.17
Mode of Physical Activity Level : 60
Variance of Physical Activity Level : 433.92
Standard Deviance of Physical Activity Level : 20.83

Max of Stress Level : 8
Min of Stress Level : 3
Range of Stress Level : 5
Mean of Stress Level : 5.39
Mode of Stress Level : 3
Variance of Stress Level : 3.15
Standard Deviance of Stress Level : 1.77

Max of Heart Rate : 86
Min of Heart Rate : 65
Range of Heart Rate : 21
Mean of Heart Rate : 70.17
Mode of Heart Rate : 68
Variance of Heart Rate : 17.1
Standard Deviance of Heart Rate : 4.14

Max of Daily Steps : 10000
Min of Daily Steps : 3000
Range of Daily Steps : 7000
Mean of Daily Steps : 6816.84
Mode of Daily Steps : 8000
Variance of Daily Steps : 2617651.14
Standard Deviance of Daily Steps : 1617.92

In [36]:
import pandas as pd
import statistics
import numpy as np

# Descriptive Statistic : Show Person with Highest & Lowest Systolic, Diastolic, and Heart Rate 
# Declaration
data = pd.read_csv("Sleep_health_and_lifestyle_dataset.csv")

# Separate Systolic and Diastolic from Blood Pressure
data[['Systolic', 'Diastolic']] = data['Blood Pressure'].str.split('/', expand=True)
data['Systolic'] = pd.to_numeric(data['Systolic'], errors='coerce')
data['Diastolic'] = pd.to_numeric(data['Diastolic'], errors='coerce')

target_col = ['Systolic','Diastolic','Heart Rate']

for dt in target_col: 
    highest_context = data[['Person ID', 'Occupation', 'Gender', 'Systolic', 'Diastolic', 'Heart Rate']].sort_values(by=dt, ascending=False).head(5)
    print(f"Highest {dt}")
    print(highest_context)
    print("\n")
    
    lowest_context = data[['Person ID', 'Occupation', 'Gender', 'Systolic', 'Diastolic', 'Heart Rate']].sort_values(by=dt, ascending=True).head(5)
    print(f"Lowest {dt}")
    print(lowest_context)
    print("\n")

Highest Systolic
     Person ID Occupation  Gender  Systolic  Diastolic  Heart Rate
264        265     Doctor    Male       142         92          83
266        267     Doctor    Male       142         92          83
373        374      Nurse  Female       140         95          68
293        294      Nurse  Female       140         95          75
287        288      Nurse  Female       140         95          75


Lowest Systolic
     Person ID  Occupation  Gender  Systolic  Diastolic  Heart Rate
118        119  Accountant  Female       115         75          68
85          86  Accountant  Female       115         75          68
142        143  Accountant  Female       115         75          68
117        118  Accountant  Female       115         75          68
140        141  Accountant  Female       115         75          68


Highest Diastolic
     Person ID Occupation  Gender  Systolic  Diastolic  Heart Rate
373        374      Nurse  Female       140         95          68
271        272      Nurse  Female       140         95          75
295        296      Nurse  Female       140         95          75
296        297      Nurse  Female       140         95          75
297        298      Nurse  Female       140         95          75


Lowest Diastolic
     Person ID  Occupation  Gender  Systolic  Diastolic  Heart Rate
136        137  Accountant  Female       115         75          68
85          86  Accountant  Female       115         75          68
138        139  Accountant  Female       115         75          68
133        134  Accountant  Female       115         75          68
130        131  Accountant  Female       115         75          68


Highest Heart Rate
     Person ID            Occupation Gender  Systolic  Diastolic  Heart Rate
277        278                Doctor   Male       139         91          86
276        277                Doctor   Male       139         91          86
3            4  Sales Representative   Male       140         90          85
4            5  Sales Representative   Male       140         90          85
5            6     Software Engineer   Male       140         90          85


Lowest Heart Rate
     Person ID Occupation  Gender  Systolic  Diastolic  Heart Rate
186        187    Teacher  Female       135         90          65
256        257    Teacher  Female       135         90          65
257        258    Teacher  Female       135         90          65
258        259    Teacher  Female       135         90          65
259        260    Teacher  Female       135         90          65

In [48]:
import pandas as pd
import statistics
import numpy as np

# Descriptive Statistic : Show Job with Average Highest & Lowest Systolic, Diastolic, and Heart Rate 
# Declaration
data = pd.read_csv("Sleep_health_and_lifestyle_dataset.csv")

# Separate Systolic and Diastolic from Blood Pressure
data[['Systolic', 'Diastolic']] = data['Blood Pressure'].str.split('/', expand=True)
data['Systolic'] = pd.to_numeric(data['Systolic'], errors='coerce')
data['Diastolic'] = pd.to_numeric(data['Diastolic'], errors='coerce')

target_col = ['Systolic','Diastolic','Heart Rate']
grouped_job = data.groupby('Occupation')[['Systolic', 'Diastolic', 'Heart Rate']].mean().round(2).reset_index()

for dt in target_col: 
    highest_context = grouped_job.sort_values(by=dt, ascending=False).head(5)
    print(f"Highest Average {dt}")
    print(highest_context)
    print("\n")
    
    lowest_context = grouped_job.sort_values(by=dt, ascending=True).head(5)
    print(f"Lowest Average {dt}")
    print(lowest_context)
    print("\n")

Highest Average Systolic
              Occupation  Systolic  Diastolic  Heart Rate
6   Sales Representative    140.00      90.00       85.00
5                  Nurse    138.52      93.73       72.00
10               Teacher    131.22      86.90       67.22
7            Salesperson    130.00      85.00       72.00
3                 Lawyer    129.96      85.00       69.64


Lowest Average Systolic
          Occupation  Systolic  Diastolic  Heart Rate
0         Accountant    117.73      76.92       68.86
1             Doctor    123.00      80.51       71.52
4            Manager    125.00      82.00       75.00
2           Engineer    125.90      81.38       67.19
9  Software Engineer    126.50      83.25       75.50


Highest Average Diastolic
              Occupation  Systolic  Diastolic  Heart Rate
5                  Nurse    138.52      93.73       72.00
6   Sales Representative    140.00      90.00       85.00
10               Teacher    131.22      86.90       67.22
8              Scientist    129.50      85.50       78.50
3                 Lawyer    129.96      85.00       69.64


Lowest Average Diastolic
          Occupation  Systolic  Diastolic  Heart Rate
0         Accountant    117.73      76.92       68.86
1             Doctor    123.00      80.51       71.52
2           Engineer    125.90      81.38       67.19
4            Manager    125.00      82.00       75.00
9  Software Engineer    126.50      83.25       75.50


Highest Average Heart Rate
             Occupation  Systolic  Diastolic  Heart Rate
6  Sales Representative    140.00      90.00        85.0
8             Scientist    129.50      85.50        78.5
9     Software Engineer    126.50      83.25        75.5
4               Manager    125.00      82.00        75.0
5                 Nurse    138.52      93.73        72.0


Lowest Average Heart Rate
    Occupation  Systolic  Diastolic  Heart Rate
2     Engineer    125.90      81.38       67.19
10     Teacher    131.22      86.90       67.22
0   Accountant    117.73      76.92       68.86
3       Lawyer    129.96      85.00       69.64
1       Doctor    123.00      80.51       71.52

In [8]:
import pandas as pd
import statistics
import numpy as np

# Descriptive Statistic : Show Gender with Average Highest & Lowest Systolic, Diastolic, and Heart Rate 
# Declaration
data = pd.read_csv("Sleep_health_and_lifestyle_dataset.csv")

# Separate Systolic and Diastolic from Blood Pressure
data[['Systolic', 'Diastolic']] = data['Blood Pressure'].str.split('/', expand=True)
data['Systolic'] = pd.to_numeric(data['Systolic'], errors='coerce')
data['Diastolic'] = pd.to_numeric(data['Diastolic'], errors='coerce')

target_col = ['Systolic','Diastolic','Heart Rate']
grouped_job = data.groupby('Gender')[['Systolic', 'Diastolic', 'Heart Rate']].mean().round(2).reset_index()

for dt in target_col: 
    highest_context = grouped_job.sort_values(by=dt, ascending=False)
    print(f"Average {dt}")
    print(highest_context)
    print("\n")

Average Systolic
   Gender  Systolic  Diastolic  Heart Rate
0  Female    130.20      86.32       69.26
1    Male    126.94      83.02       71.05


Average Diastolic
   Gender  Systolic  Diastolic  Heart Rate
0  Female    130.20      86.32       69.26
1    Male    126.94      83.02       71.05


Average Heart Rate
   Gender  Systolic  Diastolic  Heart Rate
1    Male    126.94      83.02       71.05
0  Female    130.20      86.32       69.26

In [2]:
import pandas as pd
import statistics
import numpy as np

# Descriptive Statistic : Show BMI Category with Average Highest & Lowest Systolic, Diastolic, and Heart Rate 
# Declaration
data = pd.read_csv("Sleep_health_and_lifestyle_dataset.csv")

# Separate Systolic and Diastolic from Blood Pressure
data[['Systolic', 'Diastolic']] = data['Blood Pressure'].str.split('/', expand=True)
data['Systolic'] = pd.to_numeric(data['Systolic'], errors='coerce')
data['Diastolic'] = pd.to_numeric(data['Diastolic'], errors='coerce')

target_col = ['Systolic','Diastolic','Heart Rate']
grouped_job = data.groupby('BMI Category')[['Systolic', 'Diastolic', 'Heart Rate']].mean().round(2).reset_index()

for dt in target_col: 
    highest_context = grouped_job.sort_values(by=dt, ascending=False)
    print(f"Average {dt}")
    print(highest_context)
    print("\n")

Average Systolic
    BMI Category  Systolic  Diastolic  Heart Rate
2          Obese    139.20      90.20       84.30
3     Overweight    135.05      90.18       70.95
0         Normal    123.82      80.67       68.73
1  Normal Weight    121.62      80.00       71.29


Average Diastolic
    BMI Category  Systolic  Diastolic  Heart Rate
2          Obese    139.20      90.20       84.30
3     Overweight    135.05      90.18       70.95
0         Normal    123.82      80.67       68.73
1  Normal Weight    121.62      80.00       71.29


Average Heart Rate
    BMI Category  Systolic  Diastolic  Heart Rate
2          Obese    139.20      90.20       84.30
1  Normal Weight    121.62      80.00       71.29
3     Overweight    135.05      90.18       70.95
0         Normal    123.82      80.67       68.73